arb-dir: lib/shared/ui_utils
template-arb-file: app_en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
output-dir: lib/shared/ui_utils
nullable-getter: false
preferred-supported-locales:
  - uk
  - en
